spring:
  datasource:
    url: jdbc:mysql://Localhost:3306/lost_found
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    suffix: .html
    prefix: classpath:static/

mybatis:
  mapper-locations: classpath:mappers/*.xml
